# Generated by Django 4.2.13 on 2026-05-25 22:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sap', 'SAP Fuel/Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by', models.CharField(default='analyst', max_length=100)),
                ('row_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sap', 'SAP Fuel/Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 – Direct emissions'), ('2', 'Scope 2 – Purchased energy'), ('3', 'Scope 3 – Value chain')], max_length=1)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('site_code', models.CharField(blank=True, max_length=50)),
                ('entity_name', models.CharField(blank=True, max_length=200)),
                ('raw_quantity', models.CharField(blank=True, max_length=50)),
                ('raw_unit', models.CharField(blank=True, max_length=50)),
                ('raw_date', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('flag_reasons', models.JSONField(default=list)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionbatch')),
            ],
            options={
                'ordering': ['-ingested_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='ingestion_n_source_8d11c1_idx'), models.Index(fields=['is_suspicious'], name='ingestion_n_is_susp_5f9289_idx'), models.Index(fields=['activity_date'], name='ingestion_n_activit_ef9478_idx'), models.Index(fields=['batch'], name='ingestion_n_batch_i_f490a4_idx')],
            },
        ),
    ]
