# Generated by Django 4.2.13 on 2026-05-25 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(db_index=True)),
                ('batch_id', models.IntegerField(db_index=True)),
                ('source', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('ingested', 'Ingested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged as Suspicious'), ('note_added', 'Note Added')], max_length=20)),
                ('performed_by', models.CharField(default='system', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['record_id', 'timestamp'], name='audit_audit_record__4aa621_idx')],
            },
        ),
    ]
